### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by anthonygauthier** [johrstrom/gometer#1]
Hello! 

I found this project because I was going to attempt doing something similar myself. I see that this has been pretty inactive for the past 3 years haha, would it be the kind of project you're willing to work on still? Or should I fork/base my work around what you've done? 

I read through some of the code and there are definitely some good things happening here.

Thanks!

**Comment by johrstrom** [comment]
I'd go ahead and fork it. Here's my explicit permission to just copy/paste the files without having to use this commit history.

I started this half to learn go a little bit more, but I don't believe I'll ever find the time to work on it again as I don't really use jmeter at my current position.

Drop the link for the new repo though, and I'll follow it!  Best of luck to you!
